# Generated by Django 4.2.7 on 2025-08-15 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('registered_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ثبت\u200cنام شده')),
                ('location', models.CharField(max_length=200, verbose_name='مکان')),
                ('event_type', models.CharField(choices=[('workshop', 'کارگاه'), ('seminar', 'سمینار'), ('competition', 'مسابقه'), ('meeting', 'جلسه'), ('other', 'سایر')], max_length=50, verbose_name='نوع رویداد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='برگزارکننده')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'db_table': 'events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت\u200cنام')),
                ('status', models.CharField(choices=[('registered', 'ثبت\u200cنام شده'), ('cancelled', 'لغو شده'), ('attended', 'حضور یافته')], default='registered', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='رویداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام رویداد',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای رویداد',
                'db_table': 'event_registrations',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
