# Generated by Django 4.2.7 on 2025-08-15 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('abstract', models.TextField(verbose_name='چکیده')),
                ('file', models.FileField(upload_to='articles/', verbose_name='فایل مقاله')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('revision', 'نیاز به اصلاح')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('review_comment', models.TextField(blank=True, verbose_name='نظر داور')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ارسال')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='دسته\u200cبندی')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL, verbose_name='داور')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'db_table': 'articles',
                'ordering': ['-submission_date'],
            },
        ),
    ]
